
# Создаем продавца
POST http://localhost:8000/api/v1/seller/ HTTP/1.1
content-type: application/json

{
    "first_name": "Robert",
    "last_name": "Martin",
    "email": "qew@qwe",
    "password": "201307"
}

# Получаем одного продавца по его ИД
GET http://localhost:8000/api/v1/seller/1 HTTP/1.1
content-type: application/json

##


# Создаем книгу
POST http://localhost:8000/api/v1/books/ HTTP/1.1
content-type: application/json

{
    "title": "Wrong Code",
    "author": "Robert Martin",
    "pages": 228,
    "year": 2007
}

###

# Получаем список книг
GET http://localhost:8000/api/v1/books/ HTTP/1.1

###

# Получаем одну книгу по ее ИД
GET http://localhost:8000/api/v1/books/1 HTTP/1.1

###

# Обновляем поля в данных о книге
PUT http://localhost:8000/api/v1/books/1 HTTP/1.1
content-type: application/json

{
    "title": "Clean Code",
    "author": "Robert Martin",
    "count_pages": 10,
    "year": 2007,
    "id": 0
}

###

# Удаляем книгу
DELETE http://localhost:8000/api/v1/books/1 HTTP/1.1
content-type: application/json

###